Repository dbfit/dbfit, pull requests merged in 2022-03, with the labels that each got.

#711 Add VisualStudioCode to .gitignore
  .gitignore
Labels: techtask

#710 Corrections to instructions for publishing SNAPSHOT versions
  CONTRIBUTING.md
Labels: techdebt, docs

#629 improve Connecting to the DB instructions
  website/docs/getting-started.md
Labels: docs
